#!/bin/bash

# Script to insert demo incidents into Maximo DB2
# Usage: ./insert-demo-incidents.sh [namespace] [db-name]

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# Configuration
NAMESPACE="${1:-db2u}"
DB_NAME="${2:-BLUDB}"
NUM_INCIDENTS=5

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Inserting Demo Incidents into Maximo${NC}"
echo -e "${BLUE}========================================${NC}\n"

# Check for oc command
if ! command -v oc &> /dev/null; then
    echo -e "${RED}Error: 'oc' command not found${NC}"
    exit 1
fi

# Get DB2 pod
echo -e "${BLUE}Finding DB2 pod in namespace: ${NAMESPACE}${NC}"
DB2_POD=$(oc get pods -n "$NAMESPACE" 2>/dev/null | grep db2u | grep -v Completed | grep Running | head -n 1 | awk '{print $1}')

if [ -z "$DB2_POD" ]; then
    echo -e "${RED}Error: No running DB2 pod found in namespace ${NAMESPACE}${NC}"
    echo "Try: oc get pods -n ${NAMESPACE}"
    exit 1
fi

echo -e "${GREEN}Found DB2 pod: ${DB2_POD}${NC}\n"

echo -e "${BLUE}Checking for existing current incidents (HISTORYFLAG=0)...${NC}\n"

# Check if there are any current (non-historical) incidents
INCIDENT_COUNT=$(oc exec -n "$NAMESPACE" "$DB2_POD" -- su - db2inst1 -c "db2 'CONNECT TO $DB_NAME' && db2 'SELECT COUNT(*) FROM MAXIMO.INCIDENT WHERE HISTORYFLAG = 0' && db2 'CONNECT RESET'" 2>/dev/null | grep -A1 "^-" | tail -1 | tr -d ' ')

echo "Found: $INCIDENT_COUNT current incidents"

if [ "$INCIDENT_COUNT" = "0" ] || [ -z "$INCIDENT_COUNT" ] || [ "$INCIDENT_COUNT" = "0." ]; then
    echo -e "${YELLOW}No existing incidents found. Creating incidents with minimal required fields...${NC}\n"
    
    # Insert with only the required NOT NULL fields
    oc exec -n "$NAMESPACE" "$DB2_POD" -- su - db2inst1 -c "db2 +c -t <<EOSQL
CONNECT TO $DB_NAME;
INSERT INTO MAXIMO.INCIDENT (TICKETID, TICKETUID, CLASS, STATUS, ACTLABCOST, ACTLABHRS, CHANGEBY, CHANGEDATE, HASACTIVITY, HASLD, HASSOLUTION, HISTORYFLAG, INHERITSTATUS, ISGLOBAL, ISKNOWNERROR, LANGCODE, ONCALLAUTOASSIGN, ORIGFROMALERT, PLUSPPOREQ, RELATEDTOGLOBAL, ROWSTAMP, SELFSERVSOLACCESS, SITEVISIT, STATUSDATE, TEMPLATE, DESCRIPTION, REPORTEDBY, OWNER, OWNERGROUP, SITEID, ORGID, REPORTDATE) VALUES ('INC001', 1, 'INCIDENT', 'NEW', 0, 0, 'MAXADMIN', CURRENT TIMESTAMP, 0, 0, 0, 0, 1, 0, 0, 'EN', 0, 0, 0, 0, 1, 0, 0, CURRENT TIMESTAMP, 0, 'Demo: Network connectivity issues', 'MAXADMIN', 'MAXADMIN', 'IT', 'BEDFORD', 'EAGLENA', CURRENT TIMESTAMP);
INSERT INTO MAXIMO.INCIDENT (TICKETID, TICKETUID, CLASS, STATUS, ACTLABCOST, ACTLABHRS, CHANGEBY, CHANGEDATE, HASACTIVITY, HASLD, HASSOLUTION, HISTORYFLAG, INHERITSTATUS, ISGLOBAL, ISKNOWNERROR, LANGCODE, ONCALLAUTOASSIGN, ORIGFROMALERT, PLUSPPOREQ, RELATEDTOGLOBAL, ROWSTAMP, SELFSERVSOLACCESS, SITEVISIT, STATUSDATE, TEMPLATE, DESCRIPTION, REPORTEDBY, OWNER, OWNERGROUP, SITEID, ORGID, REPORTDATE) VALUES ('INC002', 2, 'INCIDENT', 'INPROG', 0, 0, 'MAXADMIN', CURRENT TIMESTAMP, 0, 0, 0, 0, 1, 0, 0, 'EN', 0, 0, 0, 0, 1, 0, 0, CURRENT TIMESTAMP, 0, 'Demo: Email service down', 'MAXADMIN', 'MAXADMIN', 'IT', 'BEDFORD', 'EAGLENA', CURRENT TIMESTAMP);
INSERT INTO MAXIMO.INCIDENT (TICKETID, TICKETUID, CLASS, STATUS, ACTLABCOST, ACTLABHRS, CHANGEBY, CHANGEDATE, HASACTIVITY, HASLD, HASSOLUTION, HISTORYFLAG, INHERITSTATUS, ISGLOBAL, ISKNOWNERROR, LANGCODE, ONCALLAUTOASSIGN, ORIGFROMALERT, PLUSPPOREQ, RELATEDTOGLOBAL, ROWSTAMP, SELFSERVSOLACCESS, SITEVISIT, STATUSDATE, TEMPLATE, DESCRIPTION, REPORTEDBY, OWNER, OWNERGROUP, SITEID, ORGID, REPORTDATE) VALUES ('INC003', 3, 'INCIDENT', 'RESOLVED', 0, 0, 'MAXADMIN', CURRENT TIMESTAMP, 0, 0, 0, 0, 1, 0, 0, 'EN', 0, 0, 0, 0, 1, 0, 0, CURRENT TIMESTAMP, 0, 'Demo: Printer offline', 'MAXADMIN', 'MAXADMIN', 'IT', 'BEDFORD', 'EAGLENA', CURRENT TIMESTAMP);
INSERT INTO MAXIMO.INCIDENT (TICKETID, TICKETUID, CLASS, STATUS, ACTLABCOST, ACTLABHRS, CHANGEBY, CHANGEDATE, HASACTIVITY, HASLD, HASSOLUTION, HISTORYFLAG, INHERITSTATUS, ISGLOBAL, ISKNOWNERROR, LANGCODE, ONCALLAUTOASSIGN, ORIGFROMALERT, PLUSPPOREQ, RELATEDTOGLOBAL, ROWSTAMP, SELFSERVSOLACCESS, SITEVISIT, STATUSDATE, TEMPLATE, DESCRIPTION, REPORTEDBY, OWNER, OWNERGROUP, SITEID, ORGID, REPORTDATE) VALUES ('INC004', 4, 'INCIDENT', 'NEW', 0, 0, 'MAXADMIN', CURRENT TIMESTAMP, 0, 0, 0, 0, 1, 0, 0, 'EN', 0, 0, 0, 0, 1, 0, 0, CURRENT TIMESTAMP, 0, 'Demo: VPN timeout', 'MAXADMIN', 'MAXADMIN', 'IT', 'BEDFORD', 'EAGLENA', CURRENT TIMESTAMP);
INSERT INTO MAXIMO.INCIDENT (TICKETID, TICKETUID, CLASS, STATUS, ACTLABCOST, ACTLABHRS, CHANGEBY, CHANGEDATE, HASACTIVITY, HASLD, HASSOLUTION, HISTORYFLAG, INHERITSTATUS, ISGLOBAL, ISKNOWNERROR, LANGCODE, ONCALLAUTOASSIGN, ORIGFROMALERT, PLUSPPOREQ, RELATEDTOGLOBAL, ROWSTAMP, SELFSERVSOLACCESS, SITEVISIT, STATUSDATE, TEMPLATE, DESCRIPTION, REPORTEDBY, OWNER, OWNERGROUP, SITEID, ORGID, REPORTDATE) VALUES ('INC005', 5, 'INCIDENT', 'INPROG', 0, 0, 'MAXADMIN', CURRENT TIMESTAMP, 0, 0, 0, 0, 1, 0, 0, 'EN', 0, 0, 0, 0, 1, 0, 0, CURRENT TIMESTAMP, 0, 'Demo: Database slow', 'MAXADMIN', 'MAXADMIN', 'IT', 'BEDFORD', 'EAGLENA', CURRENT TIMESTAMP);
SELECT COUNT(*) AS DEMO_INCIDENTS FROM MAXIMO.INCIDENT_VIEW WHERE TICKETID IN ('INC001','INC002','INC003','INC004','INC005');
SELECT TICKETID, STATUS, DESCRIPTION FROM MAXIMO.INCIDENT_VIEW WHERE TICKETID IN ('INC001','INC002','INC003','INC004','INC005');
CONNECT RESET;
EOSQL
"
else
    echo -e "${GREEN}Found $INCIDENT_COUNT existing incidents. Copying from existing...${NC}\n"
    
    # Use the original approach with temp table
    oc exec -n "$NAMESPACE" "$DB2_POD" -- su - db2inst1 -c "db2 +c -t <<EOSQL
CONNECT TO $DB_NAME;
CREATE TABLE TEMP_INCIDENT AS (SELECT * FROM MAXIMO.INCIDENT WHERE HISTORYFLAG = 0 FETCH FIRST 1 ROWS ONLY) WITH DATA;
UPDATE TEMP_INCIDENT SET TICKETID = 'INC001', TICKETUID = (SELECT COALESCE(MAX(TICKETUID), 0) + 1 FROM MAXIMO.INCIDENT), STATUS = 'NEW', DESCRIPTION = 'Demo: Network connectivity issues', STATUSDATE = CURRENT TIMESTAMP, CHANGEDATE = CURRENT TIMESTAMP;
INSERT INTO MAXIMO.INCIDENT SELECT * FROM TEMP_INCIDENT;
UPDATE TEMP_INCIDENT SET TICKETID = 'INC002', TICKETUID = (SELECT COALESCE(MAX(TICKETUID), 0) + 1 FROM MAXIMO.INCIDENT), STATUS = 'INPROG', DESCRIPTION = 'Demo: Email service down', STATUSDATE = CURRENT TIMESTAMP, CHANGEDATE = CURRENT TIMESTAMP;
INSERT INTO MAXIMO.INCIDENT SELECT * FROM TEMP_INCIDENT;
UPDATE TEMP_INCIDENT SET TICKETID = 'INC003', TICKETUID = (SELECT COALESCE(MAX(TICKETUID), 0) + 1 FROM MAXIMO.INCIDENT), STATUS = 'RESOLVED', DESCRIPTION = 'Demo: Printer offline', STATUSDATE = CURRENT TIMESTAMP, CHANGEDATE = CURRENT TIMESTAMP;
INSERT INTO MAXIMO.INCIDENT SELECT * FROM TEMP_INCIDENT;
UPDATE TEMP_INCIDENT SET TICKETID = 'INC004', TICKETUID = (SELECT COALESCE(MAX(TICKETUID), 0) + 1 FROM MAXIMO.INCIDENT), STATUS = 'NEW', DESCRIPTION = 'Demo: VPN timeout', STATUSDATE = CURRENT TIMESTAMP, CHANGEDATE = CURRENT TIMESTAMP;
INSERT INTO MAXIMO.INCIDENT SELECT * FROM TEMP_INCIDENT;
UPDATE TEMP_INCIDENT SET TICKETID = 'INC005', TICKETUID = (SELECT COALESCE(MAX(TICKETUID), 0) + 1 FROM MAXIMO.INCIDENT), STATUS = 'INPROG', DESCRIPTION = 'Demo: Database slow', STATUSDATE = CURRENT TIMESTAMP, CHANGEDATE = CURRENT TIMESTAMP;
INSERT INTO MAXIMO.INCIDENT SELECT * FROM TEMP_INCIDENT;
DROP TABLE TEMP_INCIDENT;
SELECT COUNT(*) AS DEMO_INCIDENTS FROM MAXIMO.INCIDENT_VIEW WHERE TICKETID IN ('INC001','INC002','INC003','INC004','INC005');
SELECT TICKETID, STATUS, DESCRIPTION FROM MAXIMO.INCIDENT_VIEW WHERE TICKETID IN ('INC001','INC002','INC003','INC004','INC005');
CONNECT RESET;
EOSQL
"
fi

EXIT_CODE=$?

echo ""
if [ $EXIT_CODE -eq 0 ]; then
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}✓ Successfully inserted demo incidents${NC}"
    echo -e "${GREEN}========================================${NC}\n"
    
    echo -e "${YELLOW}Verify in your connector:${NC}"
    echo "The connector should now pick up these 5 demo incidents from the view."
    echo ""
    echo -e "${YELLOW}To view incidents directly:${NC}"
    echo "oc exec -n $NAMESPACE $DB2_POD -- su - db2inst1 -c \"db2 'CONNECT TO $DB_NAME; SELECT TICKETID, STATUS, DESCRIPTION FROM MAXIMO.INCIDENT_VIEW WHERE TICKETID LIKE \\'INC%\\' FETCH FIRST 10 ROWS ONLY'\""
else
    echo -e "${RED}========================================${NC}"
    echo -e "${RED}✗ Failed to insert incidents${NC}"
    echo -e "${RED}========================================${NC}\n"
    
    echo -e "${YELLOW}Troubleshooting:${NC}"
    echo "1. Check if there are existing incidents:"
    echo "   oc exec -n $NAMESPACE $DB2_POD -- su - db2inst1 -c \"db2 'CONNECT TO $DB_NAME; SELECT COUNT(*) FROM MAXIMO.INCIDENT WHERE HISTORYFLAG = 0'\""
    echo ""
    echo "2. Check database name:"
    echo "   oc exec -n $NAMESPACE $DB2_POD -- su - db2inst1 -c \"db2 list database directory\""
    echo ""
    echo "3. Try with different database name:"
    echo "   ./insert-demo-incidents.sh $NAMESPACE MAXDB76"
fi

exit $EXIT_CODE

# Made with Bob
