apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml

configurations:
  - namereference.yaml
  - varreference.yaml

images:
  - name: ticket-template
    newName: quay.io/jacobdanielrose/maximo-ticket-connector
    newTag: latest

# Vars removed - not needed for this deployment

patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/4/secret/secretName
      value: AIOPS-DYNAMIC-REPLACE-ELASTICSEARCHSECRETNAME
  target:
    kind: Deployment